### ISSUE TITLE
Use <div> elements to organize common structures

### ISSUE THREAD

**Issue by sdhunt** [paige-freestar/prj-rev-bwfs-dasmoto#2]
https://github.com/paige-freestar/prj-rev-bwfs-dasmoto/blob/master/dasmoto_arts_crafts/index.html#L8-L22

Notice that the three sections in the document have the same pattern. You can help the readability of your code if you group those sections with `<div>` elements, and use blank lines to accentuate the different instances. Perhaps something like this:
```
  <div class="item">
    <h2 class="brushes"> Brushes </h2>
    <img src="./resources/images/hacksaw.jpeg">
    <h3> Hacksaw Brushes </h3>
    <p> Made of the highest quality ... </p>
  </div>

  <div class="item">
    <h2 class="frames"> Frames </h2>
    <img src="./resources/images/frames.jpeg">
    <h3> Art Frames (assorted) </h3>
    <p> Assorted frames made of ... </p>
  </div>

  <div class="item">
    <h2 class="paint"> Paint </h2>
    <img src="./resources/images/finnish.jpeg">
    <h3> Clean Finnish Paint </h3>
    <p>Imported paint from ... </p>
  </div>
```
Note also, that you can now use the "item" class to target styling of those structures if you wish:

```
.item {
  ... 
}

.item h2 {
  ...
}
```

**Comment by paige-freestar** [comment]
That makes sense.
