### ISSUE TITLE
CSS Source

### ISSUE THREAD

**Issue by sdhunt** [paige-freestar/prj-rev-bwfs-dasmoto#5]
Your CSS source code is pretty good; there is no duplication, the indentation is great, and you are using the standard naming convention for classes (_all-lower-case-hyphen-delimited_).  Nice work using common class (`.pricing`) to apply the same style to multiple elements in the document.

It would improve readability if you were to include a blank line between each rule definition. 

Nice work using the global selector (`*`) to apply the font family across the document.
https://github.com/paige-freestar/prj-rev-bwfs-dasmoto/blob/42fdfebdee9afcd46a94ab623c7b0c7e42d807fb/dasmoto_arts_crafts/resources/style.css#L2
(You may want to add that missing semicolon `;` at the end of line 2, though)

**Comment by paige-freestar** [comment]
thanks for catching the ;!
